
print('# Comparison Operators')
print('>>> 42 == 42')
print(42 == 42)
print('>>> 42 == 99')
print(42 == 99)
print('>>> 2 != 3')
print(2 != 3)
print('>>> 2 != 2')
print(2 != 2)
print('>>> \'hello\' == \'hello\'')
print('hello' == 'hello')
print('>>> \'hello\' == \'Hello\'')
print('hello' == 'Hello')
print('>>> \'dog\' != \'cat\'')
print('dog' != 'cat')
print('>>> True == True')
print(True == True)
