
print('# Comparison Operators')
print('>>> 42 == 42')
print(42 == 42)
print('>>> 42 == 99')
print(42 == 99)
print('>>> 2 != 3')
print(2 != 3)
print('>>> 2 != 2')
print(2 != 2)
print('>>> \'hello\' == \'hello\'')
print('hello' == 'hello')
print('>>> \'hello\' == \'Hello\'')
print('hello' == 'Hello')
print('>>> \'dog\' != \'cat\'')
print('dog' != 'cat')
print('>>> True == True')
print(True == True)
print('>>> True != False')
print(True != False)
print('>>> 42 == 42.0')
print(42 == 42.0)
print('>>> 42 == \'42\'')
print(42 == '42')
print('>>> 42 <= 42')
print(42 <= 42)
print('>>> 29 >= 10')
print(29 >= 10)
print('# Boolean Operators')
print('>>> True and True')
print(True and True)
print('>>> True and False')
print(True and False)
print('>>> False or True')
print(False or True)
print('>>> False or False')
print(False or False)
print('>>> not True')
print(not True)
print('>>> not not not True')
print(not not not True)
print('>>> (4 < 5) and (5 < 6)')
print((4 < 5) and (5 < 6))
print('>>> (4 < 5) and (9 < 6)')
print((4 < 5) and (9 < 6))
print('>>> (1 == 2) or (2 == 2)')
print((1 == 2) or (2 == 2))
